name: MobileInv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  rename: ^3.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/eos_logo.png"

flutter_native_splash:
  color: "#ffffff"                 # warna background (wajib)
  image: "assets/images/eos_logo.png" # logo splash
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  color_dark: "#000000"             # warna bg dark mode (opsional)
  image_dark: "assets/images/eos_logo.png"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
